### ISSUE TITLE
要避免有人在 WebNode 內掃 port 去連到其他服務

### ISSUE THREAD

**Issue by ronnywang** [middle2tw/middle2#21]
要避免有人在 WebNode 內掃 port 去連到其他服務

**Comment by ctiml** [comment]
Docker 啟動加上參數 --icc=false。Containers 之間沒辦法互連

**Comment by ronnywang** [comment]
更正一下， 雖然 icu=false 可以讓 container 可以不能用 container ip 互連
但是還是可以透過 node server ip port 30001 ~ 300xx 去掃 IP 連到其他服務

不過這個問題目前沒想到可能會有什麼安全性問題，因為 node server 本來各 container 就是直接對外服務的

等到有想到問題再來 reopen 這張票

**Comment by ctiml** [comment]
有需要的話可以加一條 `iptables -A INPUT -d 172.17.0.1/32 -i docker0 -j DROP`
